package com.chatapp.mypackage;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class EditThreadPage extends javax.swing.JFrame {

    private static String threadId;
    private static String threadTitle;

    boolean did_the_window_open_first = true;

    int latestMessageId = 0;
    
    Timer timerObj = new Timer();

    /**
     * Creates new form EditThreadPage
     */
    public EditThreadPage(String threadId, String threadTitle) {
        initComponents();
        lblThreadTitle.setText("Thread Title: " + threadTitle);
        this.threadId = threadId;

        timerObj.schedule(new TimerTask() {

            @Override
            public void run() {
                showThreadMessages();
            }

        }, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTable = new javax.swing.JTable();
        lblThreadTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblThreadTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_Message = new javax.swing.JTextArea();
        btnAddMessage = new javax.swing.JButton();
        btnClearMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        messageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Edited Date", "Edited By"
            }
        ));
        messageTable.setRowHeight(30);
        messageTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(messageTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblThreadTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblThreadTitle.setText("Thread Title");

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chatapp/mypackage/back button.png"))); // NOI18N
        btnBack.setText("Back To Your Threads");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        lblThreadTitle1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblThreadTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblThreadTitle1.setText("Add Your Message Here");

        txtA_Message.setColumns(20);
        txtA_Message.setRows(5);
        txtA_Message.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(txtA_Message);

        btnAddMessage.setBackground(new java.awt.Color(102, 102, 102));
        btnAddMessage.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        btnAddMessage.setText("Add Message");
        btnAddMessage.setBorder(null);
        btnAddMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMessageActionPerformed(evt);
            }
        });

        btnClearMessage.setBackground(new java.awt.Color(102, 102, 102));
        btnClearMessage.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        btnClearMessage.setText("Clear Message");
        btnClearMessage.setBorder(null);
        btnClearMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(lblThreadTitle1))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblThreadTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClearMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblThreadTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblThreadTitle)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMessageActionPerformed
        txtA_Message.setText("");
    }//GEN-LAST:event_btnClearMessageActionPerformed

    private void btnAddMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMessageActionPerformed
        String messageContain = txtA_Message.getText();

        // this is to prompt a message to the user to let them know that they cannot send a message without typing anything.
        if (txtA_Message.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter a message in order to send");
        } else {
            addMessage(LoginPage.nickName, messageContain, this.threadId, LoginPage.userLoginId);

            txtA_Message.setText("");
        }


    }//GEN-LAST:event_btnAddMessageActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        timerObj.cancel();
        
        ThreadOptionPage threadPageObj = new ThreadOptionPage();

        threadPageObj.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void showThreadMessages() {

        String checkThreadMessage = checkNewThreadMessages(threadId, latestMessageId);

        String infoArray[] = checkThreadMessage.split("-");

        latestMessageId = Integer.parseInt(infoArray[1]);

        boolean is_a_new_message_added = Boolean.valueOf(infoArray[0]);

        if (is_a_new_message_added || did_the_window_open_first) {
            String receivedThreadChain = getThreadMessages(threadId);

            String receivedThreadChainArr[] = receivedThreadChain.split(";");

            DefaultTableModel model = (DefaultTableModel) messageTable.getModel();

            model.setRowCount(0);

            Object[] rows = new Object[3];

            int columnNo = 0;

            for (int i = 0; i < receivedThreadChainArr.length; i++) {
                String threadRowDataArr[] = receivedThreadChainArr[i].split(">");
                for (int j = 0; j < threadRowDataArr.length; j++) {
                    rows[columnNo] = threadRowDataArr[j];
                    columnNo++;
                }
                columnNo = 0;
                model.addRow(rows);
            }
            did_the_window_open_first = false;
            scrolltable();
        } else {

        }

    }

    public void scrolltable() {
        messageTable.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                messageTable.scrollRectToVisible(messageTable.getCellRect(messageTable.getRowCount() - 1, messageTable.getColumnCount(), true));
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditThreadPage(threadId, threadTitle).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMessage;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblThreadTitle;
    private javax.swing.JLabel lblThreadTitle1;
    private javax.swing.JTable messageTable;
    private javax.swing.JTextArea txtA_Message;
    // End of variables declaration//GEN-END:variables

    private static String getThreadMessages(java.lang.String threadId) {
        ChatService.ChatService_Service service = new ChatService.ChatService_Service();
        ChatService.ChatService port = service.getChatServicePort();
        return port.getThreadMessages(threadId);
    }

    private static void addMessage(java.lang.String nickName, java.lang.String message, java.lang.String threadId, java.lang.String loginId) {
        ChatService.ChatService_Service service = new ChatService.ChatService_Service();
        ChatService.ChatService port = service.getChatServicePort();
        port.addMessage(nickName, message, threadId, loginId);
    }

    private static String checkNewThreadMessages(java.lang.String threadId, int latestMessageId) {
        ChatService.ChatService_Service service = new ChatService.ChatService_Service();
        ChatService.ChatService port = service.getChatServicePort();
        return port.checkNewThreadMessages(threadId, latestMessageId);
    }

}
